//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGSColumn
    {
        public System.Guid CGSColumnId { get; set; }
        public string ColumnHeaderName { get; set; }
        public string ColumnHeaderCode { get; set; }
        public System.Guid CGSColumnType { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual CGSColumnType CGSColumnType1 { get; set; }
    }
}
