//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGSInterval
    {
        public System.Guid IntervalId { get; set; }
        public string IntervalName { get; set; }
        public int IntervalNumber { get; set; }
        public string IntervalFunction { get; set; }
        public string ActiveFlag { get; set; }
        public string Description { get; set; }
    }
}
