//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGSLinkHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGSLinkHeader()
        {
            this.CGSLinkDetails = new HashSet<CGSLinkDetail>();
            this.LinkHeaders = new HashSet<LinkHeader>();
            this.LinkDetails = new HashSet<LinkDetail>();
        }
    
        public System.Guid CGSLinkHeaderId { get; set; }
        public string Action { get; set; }
        public string ActionUrl { get; set; }
        public string AfterActionUrl { get; set; }
        public string Portal { get; set; }
        public int Timeframe { get; set; }
        public System.Guid CGSDateTimeUnit { get; set; }
    
        public virtual CGSDateTimeUnit CGSDateTimeUnit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CGSLinkDetail> CGSLinkDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkHeader> LinkHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkDetail> LinkDetails { get; set; }
    }
}
