//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGSLinkDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CGSLinkDetail()
        {
            this.LinkDetails = new HashSet<LinkDetail>();
        }
    
        public System.Guid CGSLinkDetailId { get; set; }
        public System.Guid CGSLinkHeader { get; set; }
        public string ColumnHeader { get; set; }
        public string Description { get; set; }
        public string ActiveFlag { get; set; }
        public Nullable<System.Guid> CGSColumn { get; set; }
    
        public virtual CGSLinkHeader CGSLinkHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkDetail> LinkDetails { get; set; }
    }
}
