//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CGSThemeTemplate
    {
        public System.Guid CGSThemeTemplateId { get; set; }
        public System.Guid CGSTheme { get; set; }
        public System.Guid TemplateType { get; set; }
        public string Attachment { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual CGSFileType CGSFileType { get; set; }
        public virtual CGSTheme CGSTheme1 { get; set; }
        public virtual CGSThemeTemplateType CGSThemeTemplateType { get; set; }
    }
}
