//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientActionStatus
    {
        public System.Guid ActionStatusId { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid CGSAction { get; set; }
        public System.Guid Status { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual CGSAction CGSAction1 { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
