//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceRequestStatus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientServiceRequestStatus()
        {
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.ClientServiceRequestActions = new HashSet<ClientServiceRequestAction>();
        }
    
        public System.Guid ClientServiceRequestStatusId { get; set; }
        public System.Guid Client { get; set; }
        public string Description { get; set; }
        public int SortOrder { get; set; }
        public string ActiveFlag { get; set; }
        public string DefaultFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestAction> ClientServiceRequestActions { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
