//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientAttachmentType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientAttachmentType()
        {
            this.WorkOrderAttachments = new HashSet<WorkOrderAttachment>();
            this.ServiceRequestAttachments = new HashSet<ServiceRequestAttachment>();
        }
    
        public System.Guid WorkOrderAttachmentTypeId { get; set; }
        public string Name { get; set; }
        public System.Guid Client { get; set; }
        public string ActiveFlag { get; set; }
        public string IncludeInCustomerInvoice { get; set; }
        public string ServiceRequestOrWorkOrder { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderAttachment> WorkOrderAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestAttachment> ServiceRequestAttachments { get; set; }
    }
}
