//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientActionStatuses = new HashSet<ClientActionStatus>();
            this.ClientClassOfGoods = new HashSet<ClientClassOfGood>();
            this.ClientCustomers = new HashSet<ClientCustomer>();
            this.ClientInsuranceTypes = new HashSet<ClientInsuranceType>();
            this.ClientPMHeaders = new HashSet<ClientPMHeader>();
            this.ClientProblemClasses = new HashSet<ClientProblemClass>();
            this.ClientProblemCodes = new HashSet<ClientProblemCode>();
            this.ClientResourceHeaders = new HashSet<ClientResourceHeader>();
            this.ClientServiceRequestActions = new HashSet<ClientServiceRequestAction>();
            this.ClientServiceRequestActionStatuses = new HashSet<ClientServiceRequestActionStatus>();
            this.ClientServiceRequestNoteTypes = new HashSet<ClientServiceRequestNoteType>();
            this.ClientServiceRequestPriorities = new HashSet<ClientServiceRequestPriority>();
            this.ClientServiceRequestStatuses = new HashSet<ClientServiceRequestStatus>();
            this.ClientServiceTypes = new HashSet<ClientServiceType>();
            this.ClientUsers = new HashSet<ClientUser>();
            this.ClientVendors = new HashSet<ClientVendor>();
            this.ClientWorkOrderActions = new HashSet<ClientWorkOrderAction>();
            this.ClientWorkOrderNoteTypes = new HashSet<ClientWorkOrderNoteType>();
            this.InvoiceStatuses = new HashSet<InvoiceStatus>();
            this.ServiceRequestAttachments = new HashSet<ServiceRequestAttachment>();
            this.ServiceRequestInvoiceHeaders = new HashSet<ServiceRequestInvoiceHeader>();
            this.ServiceRequestNotes = new HashSet<ServiceRequestNote>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.Statuses = new HashSet<Status>();
            this.WorkOrderAttachments = new HashSet<WorkOrderAttachment>();
            this.WorkOrderNotes = new HashSet<WorkOrderNote>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.WorkOrderVendorInvoiceHeaders = new HashSet<WorkOrderVendorInvoiceHeader>();
        }
    
        public System.Guid ClientId { get; set; }
        public string ClientName { get; set; }
        public string ActiveFlag { get; set; }
        public System.Guid Logo { get; set; }
        public string ClientAbbrv { get; set; }
        public Nullable<System.Guid> CGSTheme { get; set; }
    
        public virtual CGSThemeTemplateLogo CGSThemeTemplateLogo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientActionStatus> ClientActionStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientClassOfGood> ClientClassOfGoods { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCustomer> ClientCustomers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientInsuranceType> ClientInsuranceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPMHeader> ClientPMHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProblemClass> ClientProblemClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientProblemCode> ClientProblemCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientResourceHeader> ClientResourceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestAction> ClientServiceRequestActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestActionStatus> ClientServiceRequestActionStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestNoteType> ClientServiceRequestNoteTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestPriority> ClientServiceRequestPriorities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestStatus> ClientServiceRequestStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceType> ClientServiceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientUser> ClientUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientVendor> ClientVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientWorkOrderAction> ClientWorkOrderActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientWorkOrderNoteType> ClientWorkOrderNoteTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceStatus> InvoiceStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestAttachment> ServiceRequestAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceHeader> ServiceRequestInvoiceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestNote> ServiceRequestNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Status> Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderAttachment> WorkOrderAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderNote> WorkOrderNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderVendorInvoiceHeader> WorkOrderVendorInvoiceHeaders { get; set; }
    }
}
