//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceRequestActionStatus
    {
        public System.Guid ServiceActionStatusId { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid CGSServiceRequestActions { get; set; }
        public System.Guid InvoiceStatus { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual InvoiceStatus InvoiceStatus1 { get; set; }
        public virtual ClientServiceRequestAction ClientServiceRequestAction { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
