//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientPMHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientPMHeader()
        {
            this.PMVendors = new HashSet<PMVendor>();
            this.PMWorkOrderCreationDates = new HashSet<PMWorkOrderCreationDate>();
        }
    
        public System.Guid ClientPMHeaderId { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid Customer { get; set; }
        public System.Guid ProblemClass { get; set; }
        public System.Guid ProblemCode { get; set; }
        public System.Guid RequestPriority { get; set; }
        public System.Guid ServiceRequestType { get; set; }
        public System.Guid CreatedByUser { get; set; }
        public string CustomerReference { get; set; }
        public string IssueDescription { get; set; }
        public System.Guid Frequency { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime ArriveDateAndTime { get; set; }
        public System.DateTime FinishDateAndTime { get; set; }
        public int WOInAdvance { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual User User { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual ClientProblemClass ClientProblemClass { get; set; }
        public virtual ClientProblemCode ClientProblemCode { get; set; }
        public virtual ClientServiceRequestPriority ClientServiceRequestPriority { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMVendor> PMVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMWorkOrderCreationDate> PMWorkOrderCreationDates { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
