//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientVendorProblemClass
    {
        public System.Guid ClientVendorProblemClassesId { get; set; }
        public System.Guid ClientVendor { get; set; }
        public System.Guid ProblemClass { get; set; }
    
        public virtual ClientProblemClass ClientProblemClass { get; set; }
        public virtual ClientVendor ClientVendor1 { get; set; }
    }
}
