//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientServiceRequestAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientServiceRequestAction()
        {
            this.ClientServiceRequestActionStatuses = new HashSet<ClientServiceRequestActionStatus>();
            this.ServiceRequestActions = new HashSet<ServiceRequestAction>();
            this.ServiceRequestInvoiceActions = new HashSet<ServiceRequestInvoiceAction>();
        }
    
        public System.Guid CGSServiceRequestActionId { get; set; }
        public string ActionName { get; set; }
        public string ActionCode { get; set; }
        public System.Guid RoleGroups { get; set; }
        public string ActiveFlag { get; set; }
        public string DisplayInActionFlag { get; set; }
        public System.Guid DefaultServiceRequestStatus { get; set; }
        public Nullable<System.Guid> DefaultInvoiceStatus { get; set; }
        public string Action { get; set; }
        public Nullable<System.Guid> CGSSRAction { get; set; }
        public Nullable<System.Guid> Client { get; set; }
        public Nullable<System.Guid> DefaultServiceRequestNoteType { get; set; }
    
        public virtual CGSSRAction CGSSRAction1 { get; set; }
        public virtual ClientServiceRequestStatus ClientServiceRequestStatus { get; set; }
        public virtual RoleGroup RoleGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientServiceRequestActionStatus> ClientServiceRequestActionStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestAction> ServiceRequestActions { get; set; }
        public virtual ClientServiceRequestNoteType ClientServiceRequestNoteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceAction> ServiceRequestInvoiceActions { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
