//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientClassOfGood
    {
        public System.Guid ClassOfGoodId { get; set; }
        public System.Guid Client { get; set; }
        public string Name { get; set; }
        public string ActiveFlag { get; set; }
        public string TaxClassOfGoods { get; set; }
    
        public virtual Client Client1 { get; set; }
    }
}
