//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientUser
    {
        public System.Guid ClientUserId { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid Role { get; set; }
        public System.Guid User { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual Role Role1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
