//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientProblemCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientProblemCode()
        {
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.ClientPMHeaders = new HashSet<ClientPMHeader>();
        }
    
        public System.Guid ClientProblemCodeId { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid ClientProblemClass { get; set; }
        public string ProblemCodeName { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual ClientProblemClass ClientProblemClass1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPMHeader> ClientPMHeaders { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
