//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientWorkOrderAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClientWorkOrderAction()
        {
            this.WorkOrderActions = new HashSet<WorkOrderAction>();
        }
    
        public System.Guid ActionID { get; set; }
        public System.Guid Client { get; set; }
        public string ActionName { get; set; }
        public string Action { get; set; }
        public System.Guid DefaultNotesType { get; set; }
        public string ActiveFlag { get; set; }
        public System.Guid CGSAction { get; set; }
        public string DisplayInActionFlag { get; set; }
    
        public virtual ClientWorkOrderNoteType ClientWorkOrderNoteType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderAction> WorkOrderActions { get; set; }
        public virtual CGSAction CGSAction1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
