//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerResourceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerResourceHeader()
        {
            this.CustomerResourceDetails = new HashSet<CustomerResourceDetail>();
        }
    
        public System.Guid CustomerResourceHeadersId { get; set; }
        public System.Guid ResourceTypeHeader { get; set; }
        public System.Guid Customer { get; set; }
        public string ActiveFlag { get; set; }
        public string Alias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerResourceDetail> CustomerResourceDetails { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual ResourceTypeHeader ResourceTypeHeader1 { get; set; }
    }
}
