//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerResourceDetail
    {
        public System.Guid CustomerResourceDetailsId { get; set; }
        public System.Guid CustomerResourceHeader { get; set; }
        public System.Guid ResourceTypeDetail { get; set; }
        public string Value { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual CustomerResourceHeader CustomerResourceHeader1 { get; set; }
        public virtual ResourceTypeDetail ResourceTypeDetail1 { get; set; }
    }
}
