//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkDetail
    {
        public System.Guid LinkDetailId { get; set; }
        public System.Guid CGSLinkHeader { get; set; }
        public System.Guid CGSLinkDetails { get; set; }
        public System.Guid LinkHeader { get; set; }
        public string Value { get; set; }
    
        public virtual CGSLinkDetail CGSLinkDetail { get; set; }
        public virtual CGSLinkHeader CGSLinkHeader1 { get; set; }
        public virtual LinkHeader LinkHeader1 { get; set; }
    }
}
