//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LinkHeader()
        {
            this.LinkDetails = new HashSet<LinkDetail>();
        }
    
        public System.Guid LinkHeaderId { get; set; }
        public System.Guid CGSLinkHeader { get; set; }
        public string Action { get; set; }
        public string RandomString { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual CGSLinkHeader CGSLinkHeader1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LinkDetail> LinkDetails { get; set; }
        public virtual LinkHeader LinkHeaders1 { get; set; }
        public virtual LinkHeader LinkHeader1 { get; set; }
    }
}
