//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMVendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PMVendor()
        {
            this.PMVendorCustomerLocations = new HashSet<PMVendorCustomerLocation>();
        }
    
        public System.Guid PMVendorId { get; set; }
        public System.Guid PMHeader { get; set; }
        public System.Guid Vendor { get; set; }
        public decimal WONTE { get; set; }
        public string Description { get; set; }
    
        public virtual Vendor Vendor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMVendorCustomerLocation> PMVendorCustomerLocations { get; set; }
        public virtual ClientPMHeader ClientPMHeader { get; set; }
    }
}
