//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMVendorCustomerLocation
    {
        public System.Guid PMVendorCustomerLocationId { get; set; }
        public System.Guid CustomerLocation { get; set; }
        public System.Guid PMVendor { get; set; }
    
        public virtual CustomerLocation CustomerLocation1 { get; set; }
        public virtual PMVendor PMVendor1 { get; set; }
    }
}
