//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PMWorkOrderCreationDate
    {
        public System.Guid PMWorkOrderCreationDateId { get; set; }
        public System.Guid ClientPMHeader { get; set; }
        public Nullable<System.DateTime> WorkOrderCreationDate { get; set; }
        public System.DateTime WorkOrderArriveDate { get; set; }
        public System.DateTime WorkOrderFinishDate { get; set; }
        public Nullable<System.DateTime> WorkOrderSentDate { get; set; }
    
        public virtual ClientPMHeader ClientPMHeader1 { get; set; }
    }
}
