//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceTypeHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ResourceTypeHeader()
        {
            this.ClientResourceHeaders = new HashSet<ClientResourceHeader>();
            this.CustomerResourceHeaders = new HashSet<CustomerResourceHeader>();
            this.ResourceTypeDetails = new HashSet<ResourceTypeDetail>();
        }
    
        public System.Guid ResourceTypeHeadersId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ActiveFlag { get; set; }
        public Nullable<System.Guid> RoleGroup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientResourceHeader> ClientResourceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerResourceHeader> CustomerResourceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResourceTypeDetail> ResourceTypeDetails { get; set; }
    }
}
