//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.ServiceRequestAttachments = new HashSet<ServiceRequestAttachment>();
            this.ServiceRequestActions = new HashSet<ServiceRequestAction>();
            this.ServiceRequestNotes = new HashSet<ServiceRequestNote>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.ServiceRequestInvoiceHeaders = new HashSet<ServiceRequestInvoiceHeader>();
            this.ServiceRequestInvoiceActions = new HashSet<ServiceRequestInvoiceAction>();
        }
    
        public System.Guid ServiceRequestId { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid Customer { get; set; }
        public System.Guid CustomerLocation { get; set; }
        public System.Guid CreatedByUser { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.Guid LastUpdatedByUser { get; set; }
        public System.DateTime DateLastUpdated { get; set; }
        public System.DateTime DateWorkOrder { get; set; }
        public string CustomerRefNumber { get; set; }
        public System.Guid ClientProblemClass { get; set; }
        public System.Guid ClientProblemCode { get; set; }
        public System.Guid ClientServiceRequestPriority { get; set; }
        public System.Guid ClientServiceRequestStatus { get; set; }
        public decimal NTE { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ServiceType { get; set; }
        public string ServiceRequestNumber { get; set; }
        public string ServiceRequestNumberPrefix { get; set; }
        public Nullable<int> ServiceRequestNumberSeq { get; set; }
    
        public virtual ClientProblemClass ClientProblemClass1 { get; set; }
        public virtual ClientProblemCode ClientProblemCode1 { get; set; }
        public virtual ClientServiceRequestPriority ClientServiceRequestPriority1 { get; set; }
        public virtual ClientServiceRequestStatus ClientServiceRequestStatus1 { get; set; }
        public virtual ClientServiceType ClientServiceType { get; set; }
        public virtual CustomerLocation CustomerLocation1 { get; set; }
        public virtual Customer Customer1 { get; set; }
        public virtual Customer Customer2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestAttachment> ServiceRequestAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestAction> ServiceRequestActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestNote> ServiceRequestNotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceHeader> ServiceRequestInvoiceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceAction> ServiceRequestInvoiceActions { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
