//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestNote
    {
        public System.Guid ServiceRequestNotesId { get; set; }
        public System.Guid ServiceRequestNotesType { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid ServiceRequest { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
        public System.Guid User { get; set; }
        public string Notes { get; set; }
        public string DeleteFlag { get; set; }
    
        public virtual ClientServiceRequestNoteType ClientServiceRequestNoteType { get; set; }
        public virtual ServiceRequest ServiceRequest1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
