//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestInvoiceHeaderApiResponse
    {
        public System.Guid ServiceRequestInvoiceHeaderApiResponseId { get; set; }
        public System.Guid CartID { get; set; }
        public int ResponseType { get; set; }
        public string ResponseMessage { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public System.Guid ServiceRequestInvoiceHeader { get; set; }
    
        public virtual ServiceRequestInvoiceHeader ServiceRequestInvoiceHeader1 { get; set; }
    }
}
