//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestInvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequestInvoiceHeader()
        {
            this.ServiceRequestInvoiceDetails = new HashSet<ServiceRequestInvoiceDetail>();
            this.ServiceRequestInvoiceHeader2VendorInvoice = new HashSet<ServiceRequestInvoiceHeader2VendorInvoice>();
            this.ServiceRequestInvoiceActions = new HashSet<ServiceRequestInvoiceAction>();
            this.ServiceRequestInvoiceHeaderApiResponses = new HashSet<ServiceRequestInvoiceHeaderApiResponse>();
        }
    
        public System.Guid ServiceRequestInvoiceHeaderId { get; set; }
        public System.Guid ServiceRequest { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid Customer { get; set; }
        public string ServiceRequestInvoiceNumber { get; set; }
        public System.DateTime DateOfInvoice { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.Guid User { get; set; }
        public string InvoiceOrQuote { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> InvoiceStatus { get; set; }
        public Nullable<System.Guid> ServiceRequestAttachment { get; set; }
        public string ServiceRequestInvoicePrefix { get; set; }
        public Nullable<int> ServiceRequestInvoiceSeqNumber { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual InvoiceStatus InvoiceStatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceDetail> ServiceRequestInvoiceDetails { get; set; }
        public virtual ServiceRequest ServiceRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceHeader2VendorInvoice> ServiceRequestInvoiceHeader2VendorInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceAction> ServiceRequestInvoiceActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceHeaderApiResponse> ServiceRequestInvoiceHeaderApiResponses { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
