//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteContent
    {
        public System.Guid SiteContentID { get; set; }
        public string FileName { get; set; }
        public string Path { get; set; }
        public string ContentType { get; set; }
        public Nullable<int> Length { get; set; }
        public byte[] Data { get; set; }
        public string Text { get; set; }
        public string Roles { get; set; }
        public string RoleExceptions { get; set; }
        public string Users { get; set; }
        public string UserExceptions { get; set; }
        public string Schedule { get; set; }
        public string ScheduleExceptions { get; set; }
        public string CacheProfile { get; set; }
    }
}
