//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.ClientVendors = new HashSet<ClientVendor>();
            this.VendorUsers = new HashSet<VendorUser>();
            this.WorkOrderVendorInvoiceHeaders = new HashSet<WorkOrderVendorInvoiceHeader>();
            this.WorkOrders = new HashSet<WorkOrder>();
            this.PMVendors = new HashSet<PMVendor>();
        }
    
        public System.Guid VendorId { get; set; }
        public string VendorName { get; set; }
        public string Address01 { get; set; }
        public string Address02 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip01 { get; set; }
        public string Zip02 { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string TaxId { get; set; }
        public string TaxIdisEIN { get; set; }
        public string ActiveFlag { get; set; }
        public string AddressVerifiedFlag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientVendor> ClientVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VendorUser> VendorUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderVendorInvoiceHeader> WorkOrderVendorInvoiceHeaders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrder> WorkOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PMVendor> PMVendors { get; set; }
    }
}
