//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderVendorInvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrderVendorInvoiceHeader()
        {
            this.ServiceRequestInvoiceHeader2VendorInvoice = new HashSet<ServiceRequestInvoiceHeader2VendorInvoice>();
            this.WorkOrderVendorInvoiceDetails = new HashSet<WorkOrderVendorInvoiceDetail>();
        }
    
        public System.Guid VendorInvoiceHeaderId { get; set; }
        public System.Guid WorkOrder { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid Vendor { get; set; }
        public string VendorInvoiceNumber { get; set; }
        public System.DateTime DateOfInvoice { get; set; }
        public System.DateTime DateUpdated { get; set; }
        public System.Guid User { get; set; }
        public string InvoiceOrQuote { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> WorkOrderAttachment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestInvoiceHeader2VendorInvoice> ServiceRequestInvoiceHeader2VendorInvoice { get; set; }
        public virtual Vendor Vendor1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderVendorInvoiceDetail> WorkOrderVendorInvoiceDetails { get; set; }
        public virtual WorkOrder WorkOrder1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
