//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAction
    {
        public System.Guid WorkOrderActionID { get; set; }
        public System.Guid User { get; set; }
        public System.Guid Action { get; set; }
        public System.Guid WorkOrder { get; set; }
        public System.DateTime CurrentDate { get; set; }
        public string ActiveFlag { get; set; }
    
        public virtual ClientWorkOrderAction ClientWorkOrderAction { get; set; }
        public virtual WorkOrder WorkOrder1 { get; set; }
        public virtual User User1 { get; set; }
    }
}
