//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAttachment
    {
        public System.Guid WorkOrderAttachmentId { get; set; }
        public System.Guid WorkOrder { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid WorkOrderAttachmentType { get; set; }
        public System.DateTime UploadedDate { get; set; }
        public string FileName { get; set; }
        public System.Guid FileType { get; set; }
        public System.Guid User { get; set; }
        public string Notes { get; set; }
        public byte[] Attachment { get; set; }
        public string DisplaytoCustomer { get; set; }
    
        public virtual CGSFileType CGSFileType { get; set; }
        public virtual CGSFileType CGSFileType1 { get; set; }
        public virtual ClientAttachmentType ClientAttachmentType { get; set; }
        public virtual WorkOrder WorkOrder1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
