//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderNote
    {
        public System.Guid WorkOrderNotesId { get; set; }
        public System.Guid WorkOrderNotesType { get; set; }
        public System.Guid Client { get; set; }
        public System.Guid WorkOrder { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime UpdateDatetime { get; set; }
        public System.Guid User { get; set; }
        public string Notes { get; set; }
        public string DeleteFlag { get; set; }
    
        public virtual ClientWorkOrderNoteType ClientWorkOrderNoteType { get; set; }
        public virtual WorkOrder WorkOrder1 { get; set; }
        public virtual User User1 { get; set; }
        public virtual Client Client1 { get; set; }
    }
}
